import { useAuth } from "@/hooks/use-auth";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Send, User } from "lucide-react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
// Note: In a real integration, we'd use the chat routes generated by the integration
// For now, mocking the UI structure to match the rest of the app

export default function Messages() {
  const { user } = useAuth();
  const [message, setMessage] = useState("");

  return (
    <div className="h-[calc(100vh-4rem)] flex flex-col animate-in">
      <div className="mb-6">
        <div className="flex items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold font-display text-slate-900">Messages</h1>
            <p className="text-slate-500 mt-1">Secure communication with tenants and vendors.</p>
          </div>
        </div>
      </div>

      <Card className="flex-1 flex flex-col border-slate-200 shadow-sm overflow-hidden bg-slate-50/50">
        <div className="flex-1 p-6 space-y-6 overflow-y-auto">
          {/* Mock Messages */}
          <div className="flex gap-4 max-w-[80%]">
            <div className="w-8 h-8 rounded-full bg-slate-200 flex items-center justify-center flex-shrink-0">
              <User className="w-4 h-4 text-slate-500" />
            </div>
            <div className="bg-white p-4 rounded-2xl rounded-tl-none shadow-sm border border-slate-100">
              <p className="text-slate-800">Hi, I have a question about the lease renewal for next month.</p>
              <span className="text-xs text-slate-400 mt-2 block">10:42 AM</span>
            </div>
          </div>

          <div className="flex gap-4 max-w-[80%] ml-auto flex-row-reverse">
            <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center flex-shrink-0">
              <span className="text-white text-xs font-bold">{user?.username?.[0]}</span>
            </div>
            <div className="bg-blue-600 p-4 rounded-2xl rounded-tr-none shadow-md shadow-blue-900/10">
              <p className="text-white">Sure, I'd be happy to discuss that. What specific questions do you have?</p>
              <span className="text-xs text-blue-200 mt-2 block">10:45 AM</span>
            </div>
          </div>
        </div>

        <div className="p-4 bg-white border-t border-slate-200">
          <form className="flex gap-4" onSubmit={(e) => { e.preventDefault(); setMessage(""); }}>
            <Input 
              placeholder="Type your message..." 
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              className="flex-1 border-slate-200 bg-slate-50 focus:bg-white"
            />
            <Button type="submit" className="bg-blue-600 hover:bg-blue-700 shadow-lg shadow-blue-900/20">
              <Send className="w-4 h-4 mr-2" />
              Send
            </Button>
          </form>
        </div>
      </Card>
    </div>
  );
}
